Repository PAW-KEY/PAWKEY-Backend, pull requests merged in 2025-07, with the labels that each got.

#32 [chore] 양방향 연관관계 및 Cascade 설정, Summary 옵션 추가
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/entity/CategoryEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/entity/CategoryOptionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/infra/persistence/entity/ImageEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetTraitCategoryEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetTraitOptionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/infra/persistence/entity/RegionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/entity/ReviewEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/entity/ReviewSelectedCategoryOptionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/infra/persistence/entity/UserEntity.java
Labels: 🐥수민🐥

#39 [feat] 지역구 영역 좌표 조회 API 구현
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostCategoryOptionTop3Entity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostImageEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostLikeEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostSelectedCategoryOptionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/entity/CategoryEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/entity/CategoryOptionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/infra/persistence/entity/ImageEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetTraitCategoryEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetTraitOptionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetTraitSelectedEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/post/domain/model/Post.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/controller/RegionController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/dto/GetRegionCoordinatesResponse.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/dto/command/GetRegionCoordinatesCommand.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/dto/result/GetRegionCoordinatesResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/facade/command/GetRegionCoordinatesFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/RegionService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/RegionServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/domain/RegionRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/domain/model/Region.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/domain/vo/RegionArea.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/exception/RegionBusinessException.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/exception/RegionErrorCode.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/infra/mapper/RegionMapper.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/infra/persistence/RegionRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/infra/persistence/SpringDataRegionRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/infra/persistence/entity/RegionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/entity/ReviewEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/entity/ReviewSelectedCategoryOptionEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/entity/RouteEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/S3Controller.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/dto/response/CreateUserResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/domain/model/User.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/domain/repository/UserQueryRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/domain/repository/UserRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/exception/UserErrorCode.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/infra/mapper/UserMapper.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/infra/persistence/SpringDataUserRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/infra/persistence/UserQueryRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/infra/persistence/entity/UserEntity.java
  src/main/java/org/sopt/pawkey/backendapi/global/config/QuerydslConfig.java
  src/main/java/org/sopt/pawkey/backendapi/global/constants/AppConstants.java
  src/main/java/org/sopt/pawkey/backendapi/global/enums/GeometryType.java
  src/main/java/org/sopt/pawkey/backendapi/global/exception/GlobalErrorCode.java
  src/main/java/org/sopt/pawkey/backendapi/global/exception/S3BusinessException.java
  src/main/java/org/sopt/pawkey/backendapi/global/exception/S3ErrorCode.java
  src/main/java/org/sopt/pawkey/backendapi/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/org/sopt/pawkey/backendapi/global/infra/s3/S3ImageService.java
  src/main/java/org/sopt/pawkey/backendapi/global/util/GeoJsonUtil.java
Labels: 🫃🏻성재🫃🏻

#45 [feat] 지역 리스트 조회 api
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/controller/RegionController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/dto/GetRegionCoordinatesResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/dto/GetRegionListResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/dto/command/GetRegionListCommand.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/dto/result/GetRegionListResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/facade/query/GetRegionCoordinatesFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/facade/query/GetRegionListFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/query/RegionQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/query/RegionQueryServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/domain/RegionQueryRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/infra/persistence/RegionQueryRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/global/config/WebConfig.java
Labels: 🫃🏻성재🫃🏻, ✨ Feature

#51 [Feat] 산책 루트 정보 등록 api
  src/main/java/org/sopt/pawkey/backendapi/domain/common/ImageStorage.java
  src/main/java/org/sopt/pawkey/backendapi/domain/coordinate/Coordinate.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/application/service/command/ImageService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/application/service/command/ImageServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/domain/model/ImageType.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/domain/repository/ImageRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/infra/persistence/ImageRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/infra/persistence/SpringDataImageRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/image/infra/persistence/entity/ImageEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/api/controller/RouteController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/api/dto/RouteRegisterRequest.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/dto/command/RouteRegisterCommand.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/facade/command/RouteRegisterFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/service/command/RouteService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/service/command/RouteServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/domain/repository/RouteRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/mapper/RouteMapper.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/RouteRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/SpringDataRouteRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/entity/RouteEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/S3Controller.java
  src/main/java/org/sopt/pawkey/backendapi/global/infra/s3/S3ImageStorage.java
  src/main/java/org/sopt/pawkey/backendapi/global/response/ApiResponse.java
  src/main/java/org/sopt/pawkey/backendapi/global/util/ImageDimensionUtil.java
Labels: 🫃🏻성재🫃🏻, ✨ Feature

#56 [feat] 산책 게시물 등록 API
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/controller/PostController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/dto/request/PostCreateRequestDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/dto/command/PostCreateCommand.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/dto/command/SelectedOptionsForCategory.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/command/PostFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/command/PostLikeFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostImageService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/domain/repository/PostRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/PostRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/api/controller/CategoryController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/api/dto/response/CategoryListResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/api/dto/response/CategoryResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/application/dto/result/CategoryResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/application/service/CategoryQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/application/service/CategoryQueryServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/repository/CategoryRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/repository/SpringDataCategoryRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/application/dto/response/PetTraitCategoryResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/exception/RegionBusinessException.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/dto/result/RouteRegisterResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/facade/command/RouteRegisterFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/service/RouteService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/service/RouteServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/domain/repository/RouteRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/exception/RouteBusinessException.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/exception/RouteErrorCode.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/RouteRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/SpringDataRouteRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/TestController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/global/config/SwaggerConfig.java
Labels: 🐥수민🐥, ✨ Feature

#73 [FIX] 산책 게시물 등록 API 루트 이미지 추가 로직 삭제
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/controller/PostController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/dto/command/PostCreateCommand.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/command/PostFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostService.java
Labels: 🐥수민🐥, 🔨 Refactor

#80 [fix] 경로 저장 로직을 개선합니다
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/controller/PostController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/command/PostFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/command/PostRegisterFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostImageEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/SpringDataPostLikeRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/service/RouteServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/exception/RouteErrorCode.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/entity/RouteEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserLikedPostQueryFacade.java
Labels: 🫃🏻성재🫃🏻, 🐞 BugFix

#84 [feat] 지역구 영역 수정 API 구현
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/facade/query/GetRegionCoordinatesFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/RegionService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/RegionServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/exception/RegionErrorCode.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/facade/command/RouteRegisterFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/dto/request/UpdateUserRegionRequestDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/dto/response/UpdateUserRegionResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/dto/request/UpdateUserRegionCommand.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/command/UpdateUserRegionFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/infra/persistence/entity/UserEntity.java
  src/main/java/org/sopt/pawkey/backendapi/global/response/ApiResponse.java
Labels: 🫃🏻성재🫃🏻, ✨ Feature

#77 [feat] 공유된 트래킹 루트 좌표 정보 조회 기능 구현
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/SpringDataPostLikeRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/api/controller/RouteController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/api/dto/GetSharedRouteMapDataResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/dto/command/GetSharedRouteMapDataCommandDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/dto/result/GetSharedRouteMapDataResultDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/application/facade/query/GetSharedRouteMapDataFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/entity/RouteEntity.java
Labels: 🫃🏻성재🫃🏻, ✨ Feature

#69 [feat] 반려견 프로필 카드 조회 API
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/api/dto/response/PetProfileResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/domain/repository/PetRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/entity/PetEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/repository/PetRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/pet/infra/persistence/repository/SpringDataPetRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserPetQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserPetQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserPetQueryServiceImpl.java
Labels: 🐿️다은🐿️, ✨ Feature

#76 [feat] 내가 작성한 산책 루트 리스트 조회 API
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/domain/repository/PostRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/PostRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/SpringDataPostRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/dto/response/MyPostResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserWrittenPostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserWrittenPostQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserWrittenPostQueryServiceImpl.java
Labels: 🐿️다은🐿️, ✨ Feature

#94 [feat] 지역 조회 시 이전 지역 정보 추가
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/controller/PostController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/dto/response/PostResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/command/PostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostQueryServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/dto/GetRegionCoordinatesResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/dto/result/GetRegionCoordinatesResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/facade/query/GetRegionCoordinatesFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/dto/AuthorDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserLikedPostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/global/infra/filter/RequestLoggingFilter.java
Labels: 🫃🏻성재🫃🏻, ✨ Feature

#81 [Refactor] 저장된 산책 게시물 리스트 조회 API #48 에 대한 코드 리뷰 반영
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/entity/PostEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/SpringDataPostLikeRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserLikedPostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/infra/persistence/entity/UserEntity.java
Labels: 🐿️다은🐿️, 🔨 Refactor

#113 [fix] Category 엔티티에 order,description 항목 추가
  src/main/java/org/sopt/pawkey/backendapi/domain/category/api/dto/response/CategoryResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/application/dto/result/CategoryResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/domain/repository/CategoryRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/entity/CategoryEntity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/repository/CategoryRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/infra/persistence/repository/SpringDataCategoryRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
Labels: 🐥수민🐥, 🌚FIX

#121 [feat] 마이페이지 유저 상세 정보 조회 api
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/dto/response/UserInfoResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserQueryServiceImpl.java
Labels: 🐥수민🐥, ✨ Feature

#108 [FEATURE] 산책 게시물 리스트 필터링 조회 api
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/controller/PostController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/controller/PostFilterController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/dto/request/FilterPostsRequestDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/dto/response/PostCardResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/dto/result/GetPostCardResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/query/PostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/service/PostQueryServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/domain/repository/PostQueryRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/PostQueryRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserLikedPostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserWrittenPostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserQueryServiceImpl.java
Labels: 🐿️다은🐿️, ✨ Feature

#135 [feat] 사용자 지역 관련 유효성 검증 로직 추가
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/controller/PostController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/category/domain/repository/SelectRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/RegionService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/RegionServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/api/controller/UserController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/UserRegisterFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/command/UpdateUserRegionFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserLikedPostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/service/UserServiceImpl.java
Labels: enhancement, 🫃🏻성재🫃🏻

#137 [feat] 리뷰 등록 후, 캐싱 테이블 갱신 로직 추가
  src/main/java/org/sopt/pawkey/backendapi/domain/review/application/facade/ReviewRegisterFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/application/service/ReviewCachingService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/application/service/ReviewCachingServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/application/service/ReviewServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/domain/repository/ReviewCachingRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/domain/repository/ReviewSelectedCategoryOptionRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/ReviewCachingRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/ReviewSelectedCategoryOptionRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/SpringDataReviewCategoryOptionTop3Repository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/SpringDataReviewSelectedCategoryOptionRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/review/infra/persistence/entity/ReviewCategoryOptionTop3Entity.java
  src/main/java/org/sopt/pawkey/backendapi/domain/routes/infra/persistence/entity/RouteEntity.java
Labels: 🐥수민🐥, ✨ Feature

#140 [FEATURE] 필터링 리스트 조회 시, 내가 작성한 게시글인지 확인
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/api/dto/response/PostCardResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/dto/result/GetPostCardResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/application/facade/query/PostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/Post/infra/persistence/repository/PostQueryRepositoryImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserLikedPostQueryFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/user/application/facade/query/UserWrittenPostQueryFacade.java
Labels: 🐿️다은🐿️, ✨ Feature

#150 [feat] 대시보드> 현재 지역 조회 API
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/controller/RegionController.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/api/dto/GetRegionResponseDto.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/dto/command/GetRegionCommand.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/dto/result/GetRegionResult.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/facade/query/GetRegionFacade.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/query/RegionQueryService.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/application/service/query/RegionQueryServiceImpl.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/domain/RegionQueryRepository.java
  src/main/java/org/sopt/pawkey/backendapi/domain/region/infra/persistence/RegionQueryRepositoryImpl.java
Labels: 🐥수민🐥, ✨ Feature
